### ISSUE TITLE
Parse4cn1 Push Notifications 

### ISSUE THREAD

**Issue by andreslpz** [sidiabale/parse4cn1#13]
Hi,
   I followed the tutorial but when i send a notification from parse.com dashboard the delivery reports shows that 0 successfull deliveries and 1 outdated device.What means that? Where do you recommend me to check if i did something wrong? I reviewed the build hints and everything is like the example. 

Thank you in advance.

**Comment by sidiabale** [comment]
Hi,

Can you be more specific? Are you having issues with Android or iOS? Did
you also look at the troubleshooting sections of the guide?

Cheers
