### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jegesh** [sidiabale/parse4cn1#14]
Hi I'm trying to install your library for use with Android (at this point, and eventually iOS).  I think I followed all the instructions correctly, but all the new classes are full of errors, because they can't import Android classes, or even each other.  I think I have the wrong file tree structure, or am missing some dependencies, but looking over the documentation and your sample project I couldn't find any glaring differences. 

I declared the Android jar as a dependency, and some of the errors disappeared, but all of the Parse SDK classes seem inaccessible to my code, and to the files added when I refreshed cn1 libs.  Do you know what I need to fix?

Thanks a bunch

**Comment by sidiabale** [comment]
Hi,

It is normal for your native Android code to have errors _locally_. The important question is does your app compile when you send a build to the CN1 build servers?

PS: Do NOT add arbitrary jar dependencies to your CN1 project as that simply does not work. See this [blog post](http://www.codenameone.com/blog/jaring-and-libraries.html) for more info.

**Comment by jegesh** [comment]
I'm sorry, I put some of the files in the wrong folders.  I moved them to native/android, and now everything is compiling.  Thanks for your time, and for the great library!
