### ISSUE TITLE
Parse's hosted services will be fully retired on January 28, 2017

### ISSUE THREAD

**Issue by luiz04nl** [sidiabale/parse4cn1#16]
The Parse hosted backend will be fully retired on January 28, 2017.

What will be the parse4cn1 project going forward? will be discontinued?

**Comment by sidiabale** [comment]
See [this thread](https://groups.google.com/d/topic/codenameone-discussions/AIBF120IoiQ/discussion) on the CN1 Google group for an ongoing discussion around this topic.
