### ISSUE TITLE
parse4cn1 push notifications avaliability 

### ISSUE THREAD

**Issue by llealgt** [sidiabale/parse4cn1#27]
Hi this is not an issue(i think) but some questions(im completly new to Parse in general). My specific use case is to develop an app with push notifications i was trying firebase(with native implementation) and CN1 people suggested parse4cn1, after searching on the web im comfused, 
is it possible to develop an push app that receives push notifications? I found https://github.com/sidiabale/parse4cn1/wiki/Setting-Up-Push-For-Android  and says "for the open source Parse Server is NOT yet implemented in parse4cn1" ,is there a plan of when it will be implemented? is there any current alternative to push notifiations on parse4cn1?? y downloaded the test app(to perform this  tests) and it doesnt run on my cn1 emulator, is there any configuration neccesary ? My specific problemn is that "installation id cannot be found".

**Comment by sidiabale** [comment]
Hi,

parse4cn1 is indeed an alternative to push notifications in your app (of course, I guess you know that certain CN1 paid tiers include push notification support).

At the moment, parse4cn1 has not yet been updated for push via Parse Server. Note though that a community member has successfully done the migration for Android (see [this pull request](https://github.com/sidiabale/parse4cn1/pull/22)). I've not had the time to review/merge those changes nor to dig into the details of porting the iOS implementation.

While I don't have any concrete timeline, I'm really hoping to be able to make time for this in 2017Q1. When I do so, I'll also update the test app. In the meantime, you can draw some inspiration from the referenced work for Android.

I hope this answer helps.
