### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by jegesh** [sidiabale/parse4cn1#31]
Hi, I'm pretty sure this is an issue either with the way I  reinstalled the cn1 lib lately, or a bug in the cn1 build process, but I thought maybe you'd have some insight as to the source of the problem.  Lately I sent an iOS build, and when I tried to run the source code I got a build error from Xcode: 
`library not found for -lBolts`

I poked around on SO and decided the best thing to do was to reinstall all the cn1 libraries.  Now I have bigger problems.  Every time I send an iOS build, I get build errors.  The relevant error seems to be:

```
/var/folders/zh/kb_4hqhn4kg1h0r5dp_6htcm0000gn/T/build785158‌​1202651036597xxx/dis‌​t/MyApplication-src/‌​com_parse4cn1_encode‌​_ParseDecoder.m:308:‌​23: error: implicit declaration of function 'ca_weblite_codename1_json_JSONArray___INIT_____java_util_Ar‌​rayList' is invalid in C99 [-Werror,-Wimplicit-function-declaration] /* CustomInvoke */ca_weblite_codename1_json_JSONArray___INIT_____java_util_A‌​rrayList(threadState‌​Data, SP[-1].data.o, locals[0].data.o); SP -= 1;
```
 What do you make of this?  I already posted a [question on SO](https://stackoverflow.com/questions/45899679/codenameone-webview-not-scrollable-in-ios-version-of-app?noredirect=1#comment79426621_45899679) that Shai has given some attention to, but I haven't gotten a final answer out of him yet.

**Comment by sidiabale** [comment]
Hi, no the error doesn't ring a bell. Are you sure that while reinstalling
the library, you didn't accidentally delete some build hints?

**Comment by jegesh** [comment]
I'm pretty sure I didn't, but I will check.  Do you really think a build hint could cause an error transpiling the code from Java to Objective-C?  Maybe can you send an iOS build just to make sure it isn't an error on the build server?

**Comment by codenameone** [comment]
This is a conflict between parse4cn1 & the cn1json lib. It seems the signature of the constructor for the `JSONArray` changed from `JSONArray(ArrayList)` to `JSONArray(List)`. Seems the same to the compiler but the bytecode is different and that fails in the VM level.
Parse needs to be recompiled with up to date JSON lib and updated in the extension project.

**Comment by jegesh** [comment]
@codenameone I'm very relieved to have this resolved. Thanks for the quick response! Do you want to write up an answer on SO for posterity, or should I do it?

**Comment by codenameone** [comment]
Go ahead

**Comment by sidiabale** [comment]
Please help me understand what's happening here. A new version of the JSON
cn1lib causes parse4cn1 to break?  Does that mean the latest version of
dependencies are automatically taken? I would expect some form of
versioning...

**Comment by codenameone** [comment]
This is fixed so this issue can be closed.
In this commit: https://github.com/shannah/CN1JSON/commit/9a2d6e62470b7f8092d2b94c2c888243c62fa044#diff-3c356e17fa7df6c108d6581feee455a5

Steve changed the signature of the `JSONArray` constructor from taking `ArrayList` to taking `List`. In terms of the Java language this is 100% compatible. However,  in terms of bytcode it generates different bytecodes that might be incompatible. Since parse was compiled before that change everything broke as parse was looking for the old constructor which was no longer there.
