### ISSUE TITLE
Add badge management for iOS

### ISSUE THREAD

**Issue by sidiabale** [sidiabale/parse4cn1#9]
Expose a method in ParseInstallation to update the badge count. This will only be relevant for iOS. Current idea is to implement in native code.

See Hector's reply [here](https://parse.com/questions/how-to-reset-ios-push-notifications-badge-number-in-parse) for sample code.

**Comment by codenameone** [comment]
You don't need native code. We support badging: https://www.codenameone.com/blog/badges.html
This requires adding a build hint that you can do using the new cn1lib feature we detailed here: https://www.codenameone.com/blog/deprecations-simplified-cn1lib-installs-theme-layering.html

See the "Build Hints in cn1libs" section.

**Comment by sidiabale** [comment]
Thanks for the pointers!
